version: '3'
services:
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "8101:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alunos
      PGADMIN_DEFAULT_PASSWORD: alunos
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: estrategia
      POSTGRES_PASSWORD: 1
      
volumes:
  postgres-data:
